/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalesopsRouteImport } from './routes/salesops'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as EnergyExperienceRouteImport } from './routes/energy-experience'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CostflowRouteImport } from './routes/costflow'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildquestRouteImport } from './routes/buildquest'
import { Route as AiLaunchRouteImport } from './routes/ai-launch'
import { Route as AiIntegrationRouteImport } from './routes/ai-integration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BuildquestIndexRouteImport } from './routes/buildquest.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as BuildquestQuestsRouteImport } from './routes/buildquest.quests'
import { Route as BuildquestProfileRouteImport } from './routes/buildquest.profile'
import { Route as BuildquestKnowledgeRouteImport } from './routes/buildquest.knowledge'
import { Route as BuildquestHallRouteImport } from './routes/buildquest.hall'
import { Route as BuildquestClassSelectRouteImport } from './routes/buildquest.class-select'
import { Route as BuildquestAdminQuestsRouteImport } from './routes/buildquest.admin-quests'
import { Route as BuildquestAdminRouteImport } from './routes/buildquest.admin'
import { Route as KnowledgeCategoryIndexRouteImport } from './routes/knowledge.$category.index'
import { Route as BuildquestResultIdRouteImport } from './routes/buildquest.result.$id'
import { Route as BuildquestQuestIdRouteImport } from './routes/buildquest.quest.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesopsRoute = SalesopsRouteImport.update({
  id: '/salesops',
  path: '/salesops',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyExperienceRoute = EnergyExperienceRouteImport.update({
  id: '/energy-experience',
  path: '/energy-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CostflowRoute = CostflowRouteImport.update({
  id: '/costflow',
  path: '/costflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildquestRoute = BuildquestRouteImport.update({
  id: '/buildquest',
  path: '/buildquest',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLaunchRoute = AiLaunchRouteImport.update({
  id: '/ai-launch',
  path: '/ai-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIntegrationRoute = AiIntegrationRouteImport.update({
  id: '/ai-integration',
  path: '/ai-integration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const BuildquestIndexRoute = BuildquestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildquestRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const BuildquestQuestsRoute = BuildquestQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestProfileRoute = BuildquestProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestKnowledgeRoute = BuildquestKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestHallRoute = BuildquestHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestClassSelectRoute = BuildquestClassSelectRouteImport.update({
  id: '/class-select',
  path: '/class-select',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestAdminQuestsRoute = BuildquestAdminQuestsRouteImport.update({
  id: '/admin-quests',
  path: '/admin-quests',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestAdminRoute = BuildquestAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BuildquestRoute,
} as any)
const KnowledgeCategoryIndexRoute = KnowledgeCategoryIndexRouteImport.update({
  id: '/knowledge/$category/',
  path: '/knowledge/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildquestResultIdRoute = BuildquestResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => BuildquestRoute,
} as any)
const BuildquestQuestIdRoute = BuildquestQuestIdRouteImport.update({
  id: '/quest/$id',
  path: '/quest/$id',
  getParentRoute: () => BuildquestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-integration': typeof AiIntegrationRoute
  '/ai-launch': typeof AiLaunchRoute
  '/buildquest': typeof BuildquestRouteWithChildren
  '/contact': typeof ContactRoute
  '/costflow': typeof CostflowRoute
  '/demo': typeof DemoRoute
  '/energy-experience': typeof EnergyExperienceRoute
  '/engineering': typeof EngineeringRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salesops': typeof SalesopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/buildquest/admin': typeof BuildquestAdminRoute
  '/buildquest/admin-quests': typeof BuildquestAdminQuestsRoute
  '/buildquest/class-select': typeof BuildquestClassSelectRoute
  '/buildquest/hall': typeof BuildquestHallRoute
  '/buildquest/knowledge': typeof BuildquestKnowledgeRoute
  '/buildquest/profile': typeof BuildquestProfileRoute
  '/buildquest/quests': typeof BuildquestQuestsRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/buildquest/': typeof BuildquestIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/buildquest/quest/$id': typeof BuildquestQuestIdRoute
  '/buildquest/result/$id': typeof BuildquestResultIdRoute
  '/knowledge/$category/': typeof KnowledgeCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-integration': typeof AiIntegrationRoute
  '/ai-launch': typeof AiLaunchRoute
  '/contact': typeof ContactRoute
  '/costflow': typeof CostflowRoute
  '/demo': typeof DemoRoute
  '/energy-experience': typeof EnergyExperienceRoute
  '/engineering': typeof EngineeringRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salesops': typeof SalesopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/buildquest/admin': typeof BuildquestAdminRoute
  '/buildquest/admin-quests': typeof BuildquestAdminQuestsRoute
  '/buildquest/class-select': typeof BuildquestClassSelectRoute
  '/buildquest/hall': typeof BuildquestHallRoute
  '/buildquest/knowledge': typeof BuildquestKnowledgeRoute
  '/buildquest/profile': typeof BuildquestProfileRoute
  '/buildquest/quests': typeof BuildquestQuestsRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/buildquest': typeof BuildquestIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/buildquest/quest/$id': typeof BuildquestQuestIdRoute
  '/buildquest/result/$id': typeof BuildquestResultIdRoute
  '/knowledge/$category': typeof KnowledgeCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-integration': typeof AiIntegrationRoute
  '/ai-launch': typeof AiLaunchRoute
  '/buildquest': typeof BuildquestRouteWithChildren
  '/contact': typeof ContactRoute
  '/costflow': typeof CostflowRoute
  '/demo': typeof DemoRoute
  '/energy-experience': typeof EnergyExperienceRoute
  '/engineering': typeof EngineeringRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/insights': typeof InsightsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salesops': typeof SalesopsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/buildquest/admin': typeof BuildquestAdminRoute
  '/buildquest/admin-quests': typeof BuildquestAdminQuestsRoute
  '/buildquest/class-select': typeof BuildquestClassSelectRoute
  '/buildquest/hall': typeof BuildquestHallRoute
  '/buildquest/knowledge': typeof BuildquestKnowledgeRoute
  '/buildquest/profile': typeof BuildquestProfileRoute
  '/buildquest/quests': typeof BuildquestQuestsRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/buildquest/': typeof BuildquestIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/buildquest/quest/$id': typeof BuildquestQuestIdRoute
  '/buildquest/result/$id': typeof BuildquestResultIdRoute
  '/knowledge/$category/': typeof KnowledgeCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-integration'
    | '/ai-launch'
    | '/buildquest'
    | '/contact'
    | '/costflow'
    | '/demo'
    | '/energy-experience'
    | '/engineering'
    | '/industries'
    | '/insights'
    | '/pricing'
    | '/privacy'
    | '/salesops'
    | '/sitemap.xml'
    | '/terms'
    | '/buildquest/admin'
    | '/buildquest/admin-quests'
    | '/buildquest/class-select'
    | '/buildquest/hall'
    | '/buildquest/knowledge'
    | '/buildquest/profile'
    | '/buildquest/quests'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/buildquest/'
    | '/industries/'
    | '/insights/'
    | '/knowledge/'
    | '/buildquest/quest/$id'
    | '/buildquest/result/$id'
    | '/knowledge/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-integration'
    | '/ai-launch'
    | '/contact'
    | '/costflow'
    | '/demo'
    | '/energy-experience'
    | '/engineering'
    | '/pricing'
    | '/privacy'
    | '/salesops'
    | '/sitemap.xml'
    | '/terms'
    | '/buildquest/admin'
    | '/buildquest/admin-quests'
    | '/buildquest/class-select'
    | '/buildquest/hall'
    | '/buildquest/knowledge'
    | '/buildquest/profile'
    | '/buildquest/quests'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/buildquest'
    | '/industries'
    | '/insights'
    | '/knowledge'
    | '/buildquest/quest/$id'
    | '/buildquest/result/$id'
    | '/knowledge/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-integration'
    | '/ai-launch'
    | '/buildquest'
    | '/contact'
    | '/costflow'
    | '/demo'
    | '/energy-experience'
    | '/engineering'
    | '/industries'
    | '/insights'
    | '/pricing'
    | '/privacy'
    | '/salesops'
    | '/sitemap.xml'
    | '/terms'
    | '/buildquest/admin'
    | '/buildquest/admin-quests'
    | '/buildquest/class-select'
    | '/buildquest/hall'
    | '/buildquest/knowledge'
    | '/buildquest/profile'
    | '/buildquest/quests'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/buildquest/'
    | '/industries/'
    | '/insights/'
    | '/knowledge/'
    | '/buildquest/quest/$id'
    | '/buildquest/result/$id'
    | '/knowledge/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiIntegrationRoute: typeof AiIntegrationRoute
  AiLaunchRoute: typeof AiLaunchRoute
  BuildquestRoute: typeof BuildquestRouteWithChildren
  ContactRoute: typeof ContactRoute
  CostflowRoute: typeof CostflowRoute
  DemoRoute: typeof DemoRoute
  EnergyExperienceRoute: typeof EnergyExperienceRoute
  EngineeringRoute: typeof EngineeringRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  InsightsRoute: typeof InsightsRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SalesopsRoute: typeof SalesopsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  KnowledgeCategoryIndexRoute: typeof KnowledgeCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesops': {
      id: '/salesops'
      path: '/salesops'
      fullPath: '/salesops'
      preLoaderRoute: typeof SalesopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy-experience': {
      id: '/energy-experience'
      path: '/energy-experience'
      fullPath: '/energy-experience'
      preLoaderRoute: typeof EnergyExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costflow': {
      id: '/costflow'
      path: '/costflow'
      fullPath: '/costflow'
      preLoaderRoute: typeof CostflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildquest': {
      id: '/buildquest'
      path: '/buildquest'
      fullPath: '/buildquest'
      preLoaderRoute: typeof BuildquestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-launch': {
      id: '/ai-launch'
      path: '/ai-launch'
      fullPath: '/ai-launch'
      preLoaderRoute: typeof AiLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-integration': {
      id: '/ai-integration'
      path: '/ai-integration'
      fullPath: '/ai-integration'
      preLoaderRoute: typeof AiIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/buildquest/': {
      id: '/buildquest/'
      path: '/'
      fullPath: '/buildquest/'
      preLoaderRoute: typeof BuildquestIndexRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/buildquest/quests': {
      id: '/buildquest/quests'
      path: '/quests'
      fullPath: '/buildquest/quests'
      preLoaderRoute: typeof BuildquestQuestsRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/profile': {
      id: '/buildquest/profile'
      path: '/profile'
      fullPath: '/buildquest/profile'
      preLoaderRoute: typeof BuildquestProfileRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/knowledge': {
      id: '/buildquest/knowledge'
      path: '/knowledge'
      fullPath: '/buildquest/knowledge'
      preLoaderRoute: typeof BuildquestKnowledgeRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/hall': {
      id: '/buildquest/hall'
      path: '/hall'
      fullPath: '/buildquest/hall'
      preLoaderRoute: typeof BuildquestHallRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/class-select': {
      id: '/buildquest/class-select'
      path: '/class-select'
      fullPath: '/buildquest/class-select'
      preLoaderRoute: typeof BuildquestClassSelectRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/admin-quests': {
      id: '/buildquest/admin-quests'
      path: '/admin-quests'
      fullPath: '/buildquest/admin-quests'
      preLoaderRoute: typeof BuildquestAdminQuestsRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/admin': {
      id: '/buildquest/admin'
      path: '/admin'
      fullPath: '/buildquest/admin'
      preLoaderRoute: typeof BuildquestAdminRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/knowledge/$category/': {
      id: '/knowledge/$category/'
      path: '/knowledge/$category'
      fullPath: '/knowledge/$category/'
      preLoaderRoute: typeof KnowledgeCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildquest/result/$id': {
      id: '/buildquest/result/$id'
      path: '/result/$id'
      fullPath: '/buildquest/result/$id'
      preLoaderRoute: typeof BuildquestResultIdRouteImport
      parentRoute: typeof BuildquestRoute
    }
    '/buildquest/quest/$id': {
      id: '/buildquest/quest/$id'
      path: '/quest/$id'
      fullPath: '/buildquest/quest/$id'
      preLoaderRoute: typeof BuildquestQuestIdRouteImport
      parentRoute: typeof BuildquestRoute
    }
  }
}

interface BuildquestRouteChildren {
  BuildquestAdminRoute: typeof BuildquestAdminRoute
  BuildquestAdminQuestsRoute: typeof BuildquestAdminQuestsRoute
  BuildquestClassSelectRoute: typeof BuildquestClassSelectRoute
  BuildquestHallRoute: typeof BuildquestHallRoute
  BuildquestKnowledgeRoute: typeof BuildquestKnowledgeRoute
  BuildquestProfileRoute: typeof BuildquestProfileRoute
  BuildquestQuestsRoute: typeof BuildquestQuestsRoute
  BuildquestIndexRoute: typeof BuildquestIndexRoute
  BuildquestQuestIdRoute: typeof BuildquestQuestIdRoute
  BuildquestResultIdRoute: typeof BuildquestResultIdRoute
}

const BuildquestRouteChildren: BuildquestRouteChildren = {
  BuildquestAdminRoute: BuildquestAdminRoute,
  BuildquestAdminQuestsRoute: BuildquestAdminQuestsRoute,
  BuildquestClassSelectRoute: BuildquestClassSelectRoute,
  BuildquestHallRoute: BuildquestHallRoute,
  BuildquestKnowledgeRoute: BuildquestKnowledgeRoute,
  BuildquestProfileRoute: BuildquestProfileRoute,
  BuildquestQuestsRoute: BuildquestQuestsRoute,
  BuildquestIndexRoute: BuildquestIndexRoute,
  BuildquestQuestIdRoute: BuildquestQuestIdRoute,
  BuildquestResultIdRoute: BuildquestResultIdRoute,
}

const BuildquestRouteWithChildren = BuildquestRoute._addFileChildren(
  BuildquestRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiIntegrationRoute: AiIntegrationRoute,
  AiLaunchRoute: AiLaunchRoute,
  BuildquestRoute: BuildquestRouteWithChildren,
  ContactRoute: ContactRoute,
  CostflowRoute: CostflowRoute,
  DemoRoute: DemoRoute,
  EnergyExperienceRoute: EnergyExperienceRoute,
  EngineeringRoute: EngineeringRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  InsightsRoute: InsightsRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SalesopsRoute: SalesopsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  KnowledgeCategoryIndexRoute: KnowledgeCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
