/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesopsRouteImport } from './routes/salesops'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CostflowRouteImport } from './routes/costflow'
import { Route as AiLaunchRouteImport } from './routes/ai-launch'
import { Route as IndexRouteImport } from './routes/index'

const SalesopsRoute = SalesopsRouteImport.update({
  id: '/salesops',
  path: '/salesops',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CostflowRoute = CostflowRouteImport.update({
  id: '/costflow',
  path: '/costflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLaunchRoute = AiLaunchRouteImport.update({
  id: '/ai-launch',
  path: '/ai-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-launch': typeof AiLaunchRoute
  '/costflow': typeof CostflowRoute
  '/pricing': typeof PricingRoute
  '/salesops': typeof SalesopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-launch': typeof AiLaunchRoute
  '/costflow': typeof CostflowRoute
  '/pricing': typeof PricingRoute
  '/salesops': typeof SalesopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-launch': typeof AiLaunchRoute
  '/costflow': typeof CostflowRoute
  '/pricing': typeof PricingRoute
  '/salesops': typeof SalesopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-launch' | '/costflow' | '/pricing' | '/salesops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-launch' | '/costflow' | '/pricing' | '/salesops'
  id: '__root__' | '/' | '/ai-launch' | '/costflow' | '/pricing' | '/salesops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLaunchRoute: typeof AiLaunchRoute
  CostflowRoute: typeof CostflowRoute
  PricingRoute: typeof PricingRoute
  SalesopsRoute: typeof SalesopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salesops': {
      id: '/salesops'
      path: '/salesops'
      fullPath: '/salesops'
      preLoaderRoute: typeof SalesopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costflow': {
      id: '/costflow'
      path: '/costflow'
      fullPath: '/costflow'
      preLoaderRoute: typeof CostflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-launch': {
      id: '/ai-launch'
      path: '/ai-launch'
      fullPath: '/ai-launch'
      preLoaderRoute: typeof AiLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLaunchRoute: AiLaunchRoute,
  CostflowRoute: CostflowRoute,
  PricingRoute: PricingRoute,
  SalesopsRoute: SalesopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
